### ISSUE TITLE
azure recording kwarg is misleading

### ISSUE THREAD

**Issue by jonahpearl** [dattalab-6-cam/multicamera_acquisition#10]
We're using the `azure_recording` kwarg in `acquire_video()` to check a few things related to frame rates...let's just ask whether there's an azure in the camera list instead. It doesn't actually control whether or not an azure recording happens, which is what it implies.

**Comment by jonahpearl** [comment]
The reason I don't just change this myself is because [this line](https://github.com/timsainb/multicamera_acquisition/blob/9fd2f7934dff41309afe599b42809d434ba7e2c8/multicamera_acquisition/acquisition.py#L487) makes me think it's interacting with the arduino code in an odd way...but I think the feature this line is hinting at isn't implemented yet (having the arduino understand a num cycles wrt the basler frame rate instead of the azure frame rate)? so can we just squash that feature for now and implement it later?

**Comment by calebweinreb** [comment]
Can we close this? Seems resolved
