### ISSUE TITLE
Error if pyk4a isn't installed

### ISSUE THREAD

**Issue by calebweinreb** [dattalab-6-cam/multicamera_acquisition#35]
If pyk4a isn't installed, [this line](https://github.com/dattalab-6-cam/multicamera_acquisition/blob/86357f69f048649c661f4e03fb89674251fd0758/multicamera_acquisition/interfaces/camera_azure.py#L266) gets called anyway and causes an error. 

Maybe we can make [this line](https://github.com/dattalab-6-cam/multicamera_acquisition/blob/86357f69f048649c661f4e03fb89674251fd0758/multicamera_acquisition/acquisition.py#L423) conditional on there being azures in the config?

**Comment by jonahpearl** [comment]
Will be addressed in #40 by implementing your suggestion

**Comment by jonahpearl** [comment]
Should be fixed
